### ISSUE TITLE
How can control the time delay before the inputOptions pops up?

### ISSUE THREAD

**Issue by horaceho** [illyabusigin/CYRKeyboardButton#9]
There is a small delays before inputOptions are popup. Is there a way to control the delay interval?

**Comment by illyabusigin** [comment]
Hi @horaceho! Currently this isn't customizable. The delay is 0.3 seconds, see `setupInputOptionsConfiguration` method. I will make this customizable in a future release.

**Comment by horaceho** [comment]
Thank you!
